### ISSUE TITLE
PNG in spiffs

### ISSUE THREAD

**Issue by lidonglei1** [kikuchan/pngle#10]
hello，
  nice work！
  Could I store PNG images in SPIFFS and then use this library to display them?
  Could you give me an example？
  Thank you very much

**Comment by kikuchan** [comment]
Yes, you can display PNG images in SPIFFS, but you need to write a code to do so.

If you're using M5Stack series, the easiest way to use their library.
https://github.com/m5stack/M5Stack/blob/master/examples/Advanced/Display/png_spiffs/png_spiffs.ino

You can also find how to implement `drawPngFile`:
https://github.com/m5stack/M5Stack/blob/master/src/M5Display.cpp#L504

**Comment by lidonglei1** [comment]
> Yes, you can display PNG images in SPIFFS, but you need to write a code to do so.
> 
> If you're using M5Stack series, the easiest way to use their library. https://github.com/m5stack/M5Stack/blob/master/examples/Advanced/Display/png_spiffs/png_spiffs.ino
> 
> You can also find how to implement `drawPngFile`: https://github.com/m5stack/M5Stack/blob/master/src/M5Display.cpp#L504

Received，Thank you very much.
