### ISSUE TITLE
Add pngle to platformio library

### ISSUE THREAD

**Issue by guillempages** [kikuchan/pngle#3]
First of all, thanks for the library!

I'm trying to build a project using ESPHome, and for showing images I came across your library. I'm planning on upstreaming a new component there to show images downloaded from URL, and I'd use your library for the PNG part.

In order for your library to be integrated easily with ESPHome, it would help a lot, if it was released on platform.io.

Does this make sense in your opinion?

**Comment by kikuchan** [comment]
Thank you for trying to use the library!
It surely does make sense, but I'm not familiar with Platform.IO now, I'll try it someday.

Well, if you're using ESP series, I highly recommend to try [LovyanGFX](https://github.com/lovyan03/LovyanGFX) first, unless if you're a minimalist.
The library uses their customized version of Pngle optimized for speed. It's amazing and worthy.

**Comment by guillempages** [comment]
I'm using the ESPHome project (https://esphome.io), and I wanted to contribute the possibility of displaying online images. It is a quite complex project, so adding the minimal library is a goal AFAIK. Also, one thing that I really liked in the PNGLE library is the callback method of decoding the image; it fits very well with the rest of the ESP home. I'm not sure whether this would work with the LovyanGFX library, since the architecture of ESPHome requires a layer of indirection (i.e. not writing directly to SPI, I2C or similar).

If it is OK with you, I can try to add the required files for platformIO and do a PR; then you probably would just need to create an account there and upload it. I am not familiar with it either; I have never uploaded anything there either.
That is the documentation I found on how to upload things; if you want to take a look: https://docs.platformio.org/en/latest/librarymanager/creating.html
But again, we can try doing that in a joint effort ;-)

**Comment by kikuchan** [comment]
OK, I've released. Please try it out. :)
https://registry.platformio.org/libraries/kikuchan98/pngle

**Comment by guillempages** [comment]
Works like a charm! Thank you very much!
