### ISSUE TITLE
How to speed up computation

### ISSUE THREAD

**Issue by Gornerrrrr** [kikuchan/pngle#6]
I'm use stm32f407 and this lib to decode PNG pictures and output RGB signals.
The lib work  very well :)
But i want to speed up the decoding(now 2k picture -> 7s) .  My picture format is fixed 2k 8 Bit depth.
Have any modification suggestions for reference?  Thanks!

**Comment by Gornerrrrr** [comment]
The test picture storage in RAM. 
Size= 15.9kb; High= 1440; Width= 2560;
Decoding time=  7262ms;

**Comment by kikuchan** [comment]
Hi, thank you for using the library! :)

Please take a look at
https://github.com/lovyan03/LovyanGFX/blob/master/src/lgfx/utility/lgfx_pngle.c
This is a tuned version of pngle for speed, presented by @lovyan03
So you can find the something.

Good luck! :+1:

**Comment by Gornerrrrr** [comment]
> signals

Thanks help!
I'm try replacing this library. Now same 2k picture decoding  just need  800ms. 👍

**Comment by Gornerrrrr** [comment]
> Hi, thank you for using the library! :)
> 
> Please take a look at https://github.com/lovyan03/LovyanGFX/blob/master/src/lgfx/utility/lgfx_pngle.c This is a tuned version of pngle for speed, presented by @lovyan03 So you can find the something.
> 
> Good luck! 👍

Thanks help!
I'm try replacing this library. Now same 2k picture decoding just need 800ms. 👍
