### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jirutka** [kikuchan/pngle#8]
Can you please release/tag a new version? The latest stable (v1.0.0) doesn’t have `library.properties`, which is required by arduino/library-registry.

**Comment by kikuchan** [comment]
Thank you for your feedback!
I think I've done.

**Comment by per1234** [comment]
Thanks @kikuchan. I confirm that the registration of your library was successful following the release:

https://github.com/arduino/library-registry/pull/3438

The library will be available for installation via the [Arduino IDE Library Manager](https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-installing-a-library#installing-a-library), etc. within a day's time.

**Comment by jirutka** [comment]
Thanks!
